version: '3'

services:
  mongodb:
    image: mongo:latest
    volumes:
    - "/tmp/nodejsdata:/data/db"

  nodejs:
    depends_on:
      - mongodb
    image: dinhxkhanh/demo-service
    ports:
      - "8086:3000"
    environment:
            MONGODB_URI: mongodb://mongodb:27017/demo
            PORT: 3000
            
